apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: url
      type: string
      description: The URL of the Git repository to clone.
    - name: revision
      type: string
      description: The Git revision (branch, tag, commit) to check out.
      default: main
    - name: output
      type: string
      description: The name of the output workspace.
      default: output
    - name: subdirectory 
      type: string
      default: ""
  steps:
    - name: git-clone
      image: alpine/git
      script: |
        #!/bin/sh
        git clone -b $(params.revision) $(params.url) $(workspaces.output.path)/ ${params.subdirectories}

