apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: url
      type: string
    - name: revision
      type: string
      default: main
  workspaces:
    - name: output
  steps:
    - name: clone
      image: alpine/git
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "Cleaning output directory..."
          rm -rf /workspace/output/*
          echo "Cloning repo..."
          git clone --branch $(params.revision) $(params.url) /workspace/output
