apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: url
      type: string
    - name: revision
      type: string
      default: "main"
    - name: subdirectory
      type: string
      default: ""
  workspaces:
    - name: output
  steps:
    - name: git-clone
      image: alpine/git
      script: |
        #!/bin/bash
        echo "Cloning repository..."
        cd $(workspaces.output.path)

        # Strip https:// from the URL manually
        CLEAN_URL=$(echo "$(params.url)" | sed 's|https://||')
        git clone -b $(params.revision) https://$(params.GIT_USERNAME):$(params.GIT_PASSWORD)@$CLEAN_URL $(params.subdirectory)
      env:
        - name: credentials.username
          valueFrom:
            secretKeyRef:
              name: github-auth-secret
              key: username
        - name: credentials.password
          valueFrom:
            secretKeyRef:
              name: github-auth-secret
              key: password
