apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: url
      type: string
      description: The URL of the Git repository to clone.
    - name: revision
      type: string
      description: The Git revision (branch, tag, commit) to check out.
      default: "main"
    - name: subdirectory
      type: string
      default: ""
  workspaces:
    - name: output
      description: The workspace where the repository will be cloned
  steps:
    - name: git-clone
      image: alpine/git
      script: |
        #!/bin/sh
        git clone -b $(params.revision) $(params.url) $(workspaces.output.path)/ ${params.subdirectories}   
