apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: https://github.com/Hima0206/DevOps-assessment.git
      type: string
      description: The URL of the Git repository to clone.
    - name: revision
      type: string
      description: The Git revision (branch, tag, commit) to check out.
      default: master
    - name: subdirectories
      type: string
      default: ""
  steps:
    - name: git-clone
      image: alpine/git
      script: |
        #!/bin/sh
        git clone -b $(params.revision) $(params.url) $(workspaces.output.path)/ ${params.subdirectories}   
