apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko
spec:
  params:
    - name: IMAGE
      type: string
  workspaces:
    - name: source
      description: The workspace containing the source code.
  steps:
    - name: debug-path
      image: alpine
      script: |
        #!/bin/sh
        echo ">> DEBUG: Listing files in workspace"
        find $(workspaces.source.path)

    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      script: |
        #!/busybox/sh
        echo ">> Building Docker image..."
        /kaniko/executor \
          --dockerfile=$(workspaces.source.path)/DevOps-assessment/Dockerfile \
          --context=$(workspaces.source.path)/DevOps-assessment \
          --destination=$(params.IMAGE) \
          --insecure

