apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko
spec:
  params:
    - name: IMAGE
      type: string
  workspaces:
    - name: source
      description: The workspace containing the source code.
  steps:
    - name: debug-path
      image: alpine
      script: |
        #!/bin/sh
        echo ">> DEBUG: Listing files in workspace"
        find $(workspaces.source.path)

    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      env:
        - name: HTTP_PROXY
          value: https://127.0.0.1:8080
        - name: HTTPS_PROXY
          value: https://127.0.0.1:8080
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(workspaces.source.path)/Dockerfile
        - --context=$(workspaces.source.path)
        - --destination=$(params.IMAGE)
        - --insecure
