apiVersion: tekton.dev/v1beta1
kind: pipelinerun
metadata:
  name: rails-pipeline-run
spec:
  pipelineRef:
    name: rails-build-pipeline
  params:
    - name: git-repo
      value: https://github.com/Hima0206/DevOps-assessment.git
    - name: image url
      value: docker.io/himateja0206/my-app/general
  workspaces:
    - name:  shared-workspace
      persistentVolumeClaim:
        claimName: shared-pvcsource
      
