apiVersion: tekton.dev/v1beta1
kind: pipelinerun
metadata:
  name: rails-pipeline-run
spec:
  pipelineRef:
    name: rails-build-pipeline
  params:
    - name: git-repo
      value: https://github.com/Hima0206/DevOps-assessment.git
    - name: image url
      value: docker.io/himateja0206/rails-app:latest
  workspaces:
    - name: source
      volumeClaimTemplates:
        - metadata:
            name: source
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 1Gi 
