apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-pipeline
spec:
  params:
    - name: git-url
    - name: image-url
  workspaces:
    - name: shared-workspace
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: build-and-push
      taskRef:
        name: kaniko-build
      runAfter: ["clone"]
      params:
        - name: IMAGE
          value: $(params.image-url)
        - name: CONTEXT
          value: /workspace/shared-workspace
        - name: DOCKERFILE
          value: /workspace/shared-workspace/Dockerfile
      workspaces:
        - name: source
          workspace: shared-workspace

