apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: rails-pipeline-run
spec:
  serviceAccountName: git-serviceaccount
  pipelineRef:
    name: rails-build-pipeline
  params:
    - name: git-repo
      value: https://github.com/Hima0206/DevOps-assessment.git
    - name: image-url
      value: docker.io/himateja0206/my-app:latest
  workspaces:
    - name: source
      persistentVolumeClaim:
          claimName: shared
        
