apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-run-manual
spec:
  pipelineRef:
    name: build-pipeline
  params:
    - name: git-url
      value: https://github.com/Hima0206/DevOps-assessment.git
    - name: image-url
      value: docker.io/himateja0206/rails-app:latest
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        metadata:
          name: shared-pvc
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
  serviceAccountName: default

        
