apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rails-build-pipeline
spec:
  params:
    - name: git-repo
      type: string
      description: The URL of the Git repository to clone.
    - name: image-url
      type: string
      description: The URL of the image to build.
  workspaces:
    - name: source
      description: The workspace containing the source code.
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-repo)
      workspaces:
        - name: output
          workspace: source
    - name: build-and-push
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: $(params.image-url)
      workspaces:
        - name: source
          workspace: source


