apiVersion: v1
kind: configmap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: https://github.com/Hima0206/DevOps-assessment.git
      type: git
      name: rails-app 
